[project]
name = "youtube-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ffmpeg>=1.4",
    "pytube>=15.0.0",
    "youtube-transcript-api>=1.1.1",
    "yt-dlp>=2025.6.30",
]
