"""create actual tables

Revision ID: 554fcd758ed4
Revises: 
Create Date: 2025-07-15 06:33:45.154849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554fcd758ed4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_channels_id'), 'youtube_channels', ['id'], unique=False)
    op.create_table('youtube_videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_videos_id'), 'youtube_videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_videos_id'), table_name='youtube_videos')
    op.drop_table('youtube_videos')
    op.drop_index(op.f('ix_youtube_channels_id'), table_name='youtube_channels')
    op.drop_table('youtube_channels')
    # ### end Alembic commands ###
